"""in userDB user_name - not null

Revision ID: 1f6df63eebd5
Revises: e50dae2839e6
Create Date: 2024-08-21 16:30:05.386013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6df63eebd5'
down_revision: Union[str, None] = 'e50dae2839e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
